export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const html = `<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>بازار کانفیگ</title><style>
    *{box-sizing:border-box}body{margin:0;background:#f5f7fb;color:#17191f;font-family:system-ui,-apple-system,"Segoe UI",sans-serif}header{background:#fff;border-bottom:1px solid #e5e7eb}.wrap{max-width:1050px;margin:auto;padding:0 18px}.nav{height:64px;display:flex;align-items:center;justify-content:space-between}.logo{font-weight:800;font-size:20px}.hero{margin:28px 0;padding:42px;border-radius:24px;background:#161b26;color:#fff}.hero h1{font-size:40px;margin:10px 0}.hero p{line-height:1.8;opacity:.85}button{border:0;border-radius:10px;padding:11px 16px;background:#111;color:#fff;font-weight:700;cursor:pointer}.hero button{background:#fff;color:#111}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px}.card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:18px}.price{font-size:22px;font-weight:800;margin:16px 0}.muted{color:#6b7280}.modal{position:fixed;inset:0;background:#0008;display:grid;place-items:center;padding:20px}.box{background:#fff;border-radius:18px;padding:24px;width:min(430px,100%)}input{width:100%;padding:13px;margin:7px 0;border:1px solid #d7dbe3;border-radius:10px;font:inherit}.hidden{display:none}.orders{margin:30px 0}.order{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:14px;margin:8px 0}
    </style></head><body><header><div class="wrap nav"><div class="logo">بازار کانفیگ</div><div id="account"></div></div></header><main class="wrap"><section class="hero"><b>فروشگاه دیجیتال</b><h1>خرید و فروش کانفیگ</h1><p>بازار آنلاین کانفیگ با ورود امن از طریق ایمیل.</p><button onclick="login()">ورود / ثبت‌نام</button></section><h2>محصولات</h2><div id="products" class="grid"></div><section id="orders" class="orders hidden"><h2>سفارش‌های من</h2><div id="orderList"></div></section></main><div id="modal" class="modal hidden"><div class="box"><h2>ورود / ثبت‌نام</h2><p class="muted">لینک ورود به ایمیل شما ارسال می‌شود.</p><input id="email" type="email" placeholder="ایمیل"><input id="name" placeholder="نام (اختیاری)"><button onclick="sendLogin()">ارسال لینک ورود</button><p id="msg"></p></div></div><script>
    const $=x=>document.querySelector(x); const money=n=>new Intl.NumberFormat("fa-IR").format(n)+" تومان";
    async function api(u,o={}){let r=await fetch(u,{...o,headers:{"Content-Type":"application/json",...(o.headers||{})}});let d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"خطا");return d}
    async function load(){try{let d=await api("/api/me");$("#account").innerHTML=d.user?`<span class="muted">${d.user.email}</span> <button onclick="logout()">خروج</button>`:`<button onclick="login()">ورود</button>`;if(d.user){$("#orders").classList.remove("hidden");orders()}}catch(e){}let p=await api("/api/products");$("#products").innerHTML=p.products.length?p.products.map(x=>`<article class="card"><h3>${esc(x.title)}</h3><p class="muted">${esc(x.description||"")}</p><div class="price">${money(x.price)}</div><button onclick="buy('${x.id}')">خرید</button></article>`).join(""):"<p class=muted>هنوز محصولی ثبت نشده.</p>"}
    function login(){$("#modal").classList.remove("hidden")} async function sendLogin(){try{let d=await api("/api/auth/request",{method:"POST",body:JSON.stringify({email:$("#email").value,name:$("#name").value})});$("#msg").textContent=d.message}catch(e){$("#msg").textContent=e.message}}
    async function buy(id){try{let m=await api("/api/me");if(!m.user)return login();let d=await api("/api/orders",{method:"POST",body:JSON.stringify({productId:id})});alert("سفارش ثبت شد: "+d.orderId);orders()}catch(e){alert(e.message)}}
    async function orders(){try{let d=await api("/api/orders");$("#orderList").innerHTML=d.orders.length?d.orders.map(x=>`<div class=order><b>${esc(x.title)}</b> — ${money(x.amount)} — ${esc(x.status)}</div>`).join(""):"<p class=muted>سفارشی ندارید.</p>"}catch(e){}}
    async function logout(){await api("/api/auth/logout",{method:"POST"});location.reload()} function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))} load();
    </script></body></html>`;

    const now=()=>Math.floor(Date.now()/1000);
    const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json;charset=UTF-8"}});
    async function hash(v){let b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
    function token(){let b=new Uint8Array(32);crypto.getRandomValues(b);return btoa(String.fromCharCode(...b)).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}
    function cookie(req){return (req.headers.get("Cookie")||"").match(/(?:^|;\s*)session=([^;]+)/)?.[1]}
    async function user(){let t=cookie(request);if(!t||!env.DB)return null;return env.DB.prepare("SELECT u.id,u.email,u.name,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?").bind(await hash(t),now()).first()}

    if(url.pathname==="/api/products"){let r=await env.DB.prepare("SELECT id,title,description,price,created_at FROM products WHERE active=1 ORDER BY created_at DESC").all();return json({products:r.results})}
    if(url.pathname==="/api/products/" && request.method==="GET")return json({error:"محصول پیدا نشد"},404)
    if(url.pathname==="/api/me"){return json({user:await user()})}
    if(url.pathname==="/api/auth/logout"&&request.method==="POST"){let t=cookie(request);if(t)await env.DB.prepare("DELETE FROM sessions WHERE token_hash=?").bind(await hash(t)).run();return new Response(JSON.stringify({ok:true}),{headers:{"content-type":"application/json","Set-Cookie":"session=; Max-Age=0; Path=/; HttpOnly; Secure; SameSite=Lax"}})}
    if(url.pathname==="/api/auth/request"&&request.method==="POST"){
      let {email,name}=await request.json();email=String(email||"").trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json({error:"ایمیل معتبر وارد کنید."},400);
      let u=await env.DB.prepare("SELECT * FROM users WHERE email=?").bind(email).first();if(!u){let id=crypto.randomUUID();await env.DB.prepare("INSERT INTO users(id,email,name,role,created_at) VALUES(?,?,?,?,?)").bind(id,email,String(name||"").trim(), "buyer",now()).run();u={id,email}}
      let raw=token();await env.DB.prepare("INSERT INTO login_tokens(token_hash,user_id,expires_at,used) VALUES(?,?,?,0)").bind(await hash(raw),u.id,now()+900).run();
      let link=`${env.APP_URL}/api/auth/verify?token=${encodeURIComponent(raw)}`;
      let r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{"Authorization":`Bearer ${env.RESEND_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({from:env.RESEND_FROM,to:[email],subject:"ورود به بازار کانفیگ",html:`<div dir="rtl"><h2>ورود به حساب</h2><p>برای ورود روی لینک زیر بزنید:</p><p><a href="${link}">ورود به حساب</a></p><p>این لینک ۱۵ دقیقه معتبر است.</p></div>`})});
      if(!r.ok)return json({error:"ارسال ایمیل انجام نشد."},500);return json({ok:true,message:"لینک ورود به ایمیل شما ارسال شد."})
    }
    if(url.pathname==="/api/auth/verify"){let raw=url.searchParams.get("token");if(!raw)return new Response("توکن نامعتبر است",{status:400});let x=await env.DB.prepare("SELECT * FROM login_tokens WHERE token_hash=? AND used=0 AND expires_at>?").bind(await hash(raw),now()).first();if(!x)return new Response("لینک منقضی یا استفاده شده است",{status:400});await env.DB.prepare("UPDATE login_tokens SET used=1 WHERE token_hash=?").bind(await hash(raw)).run();let s=token();await env.DB.prepare("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)").bind(await hash(s),x.user_id,now()+2592000).run();return new Response(null,{status:302,headers:{"Location":"/","Set-Cookie":`session=${s}; Max-Age=2592000; Path=/; HttpOnly; Secure; SameSite=Lax`}})}
    if(url.pathname==="/api/orders"&&request.method==="POST"){let u=await user();if(!u)return json({error:"ابتدا وارد شوید."},401);let {productId}=await request.json();let p=await env.DB.prepare("SELECT id,price FROM products WHERE id=? AND active=1").bind(productId).first();if(!p)return json({error:"محصول پیدا نشد."},404);let id=crypto.randomUUID();await env.DB.prepare("INSERT INTO orders(id,buyer_id,product_id,amount,status,created_at) VALUES(?,?,?,?,?,?)").bind(id,u.id,p.id,p.price,"pending",now()).run();return json({ok:true,orderId:id})}
    if(url.pathname==="/api/orders"){let u=await user();if(!u)return json({error:"ابتدا وارد شوید."},401);let r=await env.DB.prepare("SELECT o.id,o.amount,o.status,o.created_at,p.title FROM orders o JOIN products p ON p.id=o.product_id WHERE o.buyer_id=? ORDER BY o.created_at DESC").bind(u.id).all();return json({orders:r.results})}
    return new Response(html,{headers:{"content-type":"text/html;charset=UTF-8"}});
  }
};
